# This docker-compose is to be used in development environment only.

version: "3"
services:
  hello-world:
    build:
      context: .
      dockerfile: devops/Dockerfile
    ports:
      - "8080:8080"
