name: Build and Deploy

on:
  push:
    brnanches: ["main"]
    paths:
      - "src/**"
      - "devops/**"
    

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_tag.outputs.TAG }}
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle' 
 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Generate Tag Number
        id: set_tag
        run: |
          VERSION="version-${{ github.run_number }}"
          echo "TAG=$VERSION" >> $GITHUB_ENV
          echo "TAG=$VERSION" >> $GITHUB_OUTPUT  # Save output

      - name: Grant execute permissions to Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
 
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image with Context
        uses: docker/build-push-action@v6
        with:
          context: .
          file: devops/Dockerfile
          push: true
          tags: "muk007/spring-boot:${{ env.TAG }}"

  deploy:
    needs: build
    uses: devops-contribution/reusable-workflows/.github/workflows/reusable-template.yaml@main
    with:
      file_path: "manifests/apps/micro-service-101/overlays/dev/deployment-patch.yaml"
      pr_title: "Bump version to ${{ needs.build.outputs.image_tag }}"
      pr_body: "Automated update of application version."
      branch_name: "update-tag-${{ needs.build.outputs.image_tag }}"
      updated_version: "spring-boot:${{ needs.build.outputs.image_tag }}"
      channel_id: "C08BAR4AXCH"
      service_name: "service: micro-service-101"
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
