name: Build


on:
  push:
    brnanches: ["main"]


jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_tag.outputs.TAG }}
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle' 
 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2


      - name: Generate Tag Number
        id: set_tag
        run: |
          VERSION="version-${{ github.run_number }}"
          echo "TAG=$VERSION" >> $GITHUB_ENV
          echo "TAG=$VERSION" >> $GITHUB_OUTPUT  # Save output

      - name: Grant execute permissions to Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
 
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build the Docker image
        run: |
          echo "Building image with tag: $TAG"
          docker build -t ${{ secrets.DOCKER_USERNAME }}/spring-boot:"$TAG" -f devops/Dockerfile .

      - name: Push the Docker image to Docker Hub
        run: |
          echo "Pushing image with tag: $TAG"
          docker push ${{ secrets.DOCKER_USERNAME }}/spring-boot:"$TAG"
